
import '../models/book_model.dart';

class BookController {
  List<BookModel> get books {
    return [
      BookModel(
        id: 1,
        title: "Kursi Hitam",
        author: "Yoshitoki Oima",
        overview: "Sebuah novel tentang penerimaan diri dan pengampunan.",
        publisher: "Kodansha",
        status: "Available",
        rating: 4.9,
        posterPath: "assets/images/Buku1.jpg",
        available: 3,
      ),
      BookModel(
        id: 2,
        title: "The Other Side",
        author: "Adachitoka",
        overview: "Cerita tentang dewa yang tidak memiliki kuil dan seorang gadis manusia.",
        publisher: "Kodansha",
        status: "Available",
        rating: 4.7,
        posterPath: "assets/images/buku2.jpg",
        available: 5,
      ),
      BookModel(
        id: 3,
        title: "Sunset",
        author: "Makoto Shinkai",
        overview: "Sebuah kisah cinta antara dua orang dari dunia berbeda.",
        publisher: "Kadokawa",
        status: "Available",
        rating: 4.8,
        posterPath: "assets/images/buku3.jpg",
        available: 4,
      ),
      BookModel(
        id: 4,
        title: "Forest",
        author: "Yoshitoki Oima",
        overview: "Kisah tentang penerimaan diri dan pengampunan.",
        publisher: "Kodansha",
        status: "Available",
        rating: 4.9,
        posterPath: "assets/images/buku4.jpg",
        available: 2,
      ),
      BookModel(
        id: 5,
        title: "Alone",
        author: "Eiichiro Oda",
        overview: "Petualangan bajak laut Luffy mencari harta karun legendaris.",
        publisher: "Shueisha",
        status: "Available",
        rating: 4.9,
        posterPath: "assets/images/buku6.jpg",
        available: 6,
      ),
      BookModel(
        id: 6,
        title: "Cargo",
        author: "Natsume Akatsuki",
        overview: "Kisah lucu tentang petualangan di dunia fantasi.",
        publisher: "Kadokawa",
        status: "Available",
        rating: 4.5,
        posterPath: "assets/images/buku9.jpg",
        available: 3,
      ),
      BookModel(
        id: 7,
        title: "LightFall",
        author: "Hayao Miyazaki",
        overview: "Petualangan seorang gadis di dunia roh yang ajaib.",
        publisher: "Studio Ghibli",
        status: "Available",
        rating: 4.8,
        posterPath: "assets/images/Carousel1.jpg",
        available: 4,
      ),
      BookModel(
        id: 8,
        title: "nostos",
        author: "Makoto Shinkai",
        overview: "Sebuah kisah cinta antara dua orang dari dunia berbeda.",
        publisher: "Kadokawa",
        status: "Available",
        rating: 4.8,
        posterPath: "assets/images/carousel2.jpg",
        available: 4,
      ),
      BookModel(
        id: 9,
        title: "Guardian Tales",
        author: "Yoshitoki Oima",
        overview: "Kisah tentang penerimaan diri dan pengampunan.",
        publisher: "Kodansha",
        status: "Available",
        rating: 4.9,
        posterPath: "assets/images/carousel3.jpg",
        available: 2,
      ),
      BookModel(
        id: 10,
        title: "Beasts",
        author: "Eiichiro Oda",
        overview: "Petualangan bajak laut Luffy mencari harta karun legendaris.",
        publisher: "Shueisha",
        status: "Available",
        rating: 4.9,
        posterPath: "assets/images/carousel4.jpg",
        available: 6,
      ),
      BookModel(
        id: 11,
        title: "The Legend Of Zelda",
        author: "Natsume Akatsuki",
        overview: "Kisah lucu tentang petualangan di dunia fantasi.",
        publisher: "Kadokawa",
        status: "Available",
        rating: 4.5,
        posterPath: "assets/images/carousel5.jpg",
        available: 3,
      ),
      BookModel(
        id: 12,
        title: "Tentang Kamu",
        author: "Adachitoka",
        overview: "Cerita tentang dewa yang tidak memiliki kuil dan seorang gadis manusia.",
        publisher: "Kodansha",
        status: "Available",
        rating: 4.7,
        posterPath: "assets/images/Tentang_kamu.jpg",
        available: 5,
      ),
      
    ];
  }
}